name: build

defaults:
  run:
    shell: bash

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Run container build script
        run: |
          ./build/run-container.sh

