name: build

defaults:
  run:
    shell: bash

on:
  push:
    tags: ['v*']

env:
  BIN_NAME: turing-machine-static

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Run container build script
        run: |
          ./build/run-container.sh
      - name: Rename file
        run: |
          mv turing-machine "$BIN_NAME"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BIN_NAME }}
          path: ${{ env.BIN_NAME }}
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.BIN_NAME }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.BIN_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

