name: build

defaults:
  run:
    shell: bash

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Run container build script
        run: |
          ./build/run-container.sh
      - uses: actions/upload-artifact@v2
        with:
          name: turing-machine
          path: turing-machine
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: turing-machine
      - uses: ncipollo/release-action@v1
        with:
          artifacts: turing-machine
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

